controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_articles_search:
    path: '/search'
    controller: 'App\Controller\ArticlesController::searchByTitle'
    methods: ['GET']
